function mainLog = importfile_log_waterlinked(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MAINLOG = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  MAINLOG = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  mainLog = importfile("/home/pierre-ifremer/Downloads/Logs waterlinked/Test_14,4m_20min_50cm/mainLog.log", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Jun-2021 17:27:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 29);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ", ","];

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "rover_app", "VarName6", "INFO", "VarName8", "Start", "FollowMe", "Application", "at", "Thu", "Jun", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29"];
opts.VariableTypes = ["datetime", "datetime", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "categorical", "categorical", "double", "categorical", "double", "double", "string", "string", "categorical", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName25", "VarName26"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName4", "rover_app", "VarName6", "INFO", "VarName8", "Start", "FollowMe", "Application", "at", "Thu", "Jun", "VarName15", "VarName16", "VarName19", "VarName20", "VarName22", "VarName25", "VarName26", "VarName27", "VarName28"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "VarName1", "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, "VarName2", "InputFormat", "HH:mm:ss");
opts = setvaropts(opts, "VarName17", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName17", "ThousandsSeparator", ",");

% Import the data
mainLog = readtable(filename, opts);

end