function create_figure_article_1_heading_speed(YMatrix1, axes2, YMatrix2)
%CREATEFIGURE(YMatrix1, axes2, YMatrix2)
%  YMATRIX1:  matrix of y data
%  AXES2:  legend axes
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 06-Dec-2021 09:39:14

% Create figure
figure('OuterPosition',[409 375 737 591]);

% Create axes
axes1 = axes('Position',...
    [0.424410540915395 0.11 0.553398058252427 0.377951807228916]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1);
set(plot1(1),'DisplayName','SAAM','Color',[1 0 0]);
set(plot1(2),'DisplayName','Madgwick','Color',[0 0 1]);
set(plot1(3),'Color',[1 0 0]);
set(plot1(4),'LineWidth',1,'Color',[0 0 1]);

% Create ylabel
ylabel('Heading error (°)','FontWeight','bold','FontSize',12);

% Create xlabel
xlabel('Sample number');

% Create title
title('c) Heading estimation error','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1000 23000]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'LineWidth',1);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.806380030570678 0.395800579447918 0.16920942841059 0.0853413631877745],...
    'FontWeight','bold',...
    'FontSize',11);

% Create legend
legend2 = legend(axes2,'show');
set(legend2,...
    'Position',[0.00196078089921065 0.76423388618382 0.357836329862579 0.229919672431237],...
    'FontWeight','bold',...
    'FontSize',12);
title(legend2,' a) Georeferenced trajectories');

% Create axes
axes3 = axes('Position',...
    [0.42995839112344 0.583837209302326 0.554785020804438 0.359937891099281]);
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'LineWidth',1);
set(plot2(1),'DisplayName','ODBA Regression','Color',[1 0 0]);
set(plot2(2),'DisplayName','Speed sensor Regression','MarkerSize',10,...
    'Color',[0 0 1]);
set(plot2(3),'DisplayName','Speed reference','Color',[0 0 0]);

% Create ylabel
ylabel('Error speed (m/s)','FontWeight','bold','FontSize',12);

% Create title
title('b) Speed estimation error','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[1000 23000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 1.5]);
box(axes3,'on');
hold(axes3,'off');
% Create legend
legend3 = legend(axes3,'show');
set(legend3,...
    'Position',[0.66837726104772 0.81447528086501 0.321775304584993 0.124497988556763],...
    'FontWeight','bold',...
    'FontSize',11);

